[package]
name = "typst-resume-tabluary-cv"
version = "0.1.0"
entrypoint = "cv.typ"
authors = ["Freddy"]
description = "Multilingual Typst CV and cover letter template with table-based layout"
license = "MIT"
